name: Ruby Test
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        ruby: [2.5, 2.6, 2.7, 3.0]
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby ${{ matrix.ruby }}
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install gems
      run: |
        gem install bundler --force --no-document
        bundle install --jobs 4 --retry 3
    - run: bundle exec rake
    - run: bundle exec rubocop
    - run: ./bin/bgem
    - run: ./bin/bgem list
    - run: ./bin/bgem install rake
