name: Install RuboCop and Run
on: [push]
jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Ruby 2.6.x
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Install RuboCop and Run
      run: |
        bundle install
        ./bin/bgem list --lockfile test/fixture/Gemfile.sample.lock
        ./bin/bgem install rubocop --lockfile test/fixture/Gemfile.sample.lock
        rubocop --version
