name: Install RuboCop and Run
on: [push]
jobs:
  sample:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Install RuboCop and Run
      run: |
        bundle install --without development
        ./bin/bgem list --lockfile test/fixture/Gemfile.sample.lock
        ./bin/bgem install rubocop --lockfile test/fixture/Gemfile.sample.lock
        rubocop --version
